### ISSUE TITLE
音符频率如何算？

### ISSUE THREAD

**Issue by MlgmXyysd** [chchlsh/MusicBox#1]
通过查各种资料把音符上一二三个点和音符下一二个点的频率列了出来，现在还差音符下三个点1-7的频率

**Comment by MlgmXyysd** [comment]
![QQ截图20190903195644](https://user-images.githubusercontent.com/17919858/64171336-fdc40e00-ce84-11e9-977f-056fd3c0279a.png)

**Comment by chchlsh** [comment]
这个就涉及到乐理了，我不是专业搞音乐的，对乐理其实也不太懂，但从网上看的意思是相邻的两个半音之比是相等的，而根据十二平均律，从1到高音1之间一共有12个半音，这样我们就能根据前面音的频率来计算后面音的频率了，具体怎么算嘛，还是百度吧，我也是业余的

**Comment by MlgmXyysd** [comment]
刚才查AudioContext API资料的时候看见一个文章里面有这个：https://denzel.netlify.com/js/useful_webapis_audiocontext.html




------------------ 原始邮件 ------------------
发件人: "王睿"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 晚上8:22
收件人: "chchlsh/MusicBox"<MusicBox@noreply.github.com>; 
抄送: "mlgmxyysd"<1204074991@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [chchlsh/MusicBox] 音符频率如何算？ (#1)




这个就涉及到乐理了，我不是专业搞音乐的，对乐理其实也不太懂，但从网上看的意思是相邻的两个半音之比是相等的，而根据十二平均律，从1到高音1之间一共有12个半音，这样我们就能根据前面音的频率来计算后面音的频率了，具体怎么算嘛，还是百度吧，我也是业余的

**Comment by MlgmXyysd** [comment]
OK，我再去查查




------------------ 原始邮件 ------------------
发件人: "王睿"<notifications@github.com>; 
发送时间: 2019年9月3日(星期二) 晚上8:22
收件人: "chchlsh/MusicBox"<MusicBox@noreply.github.com>; 
抄送: "mlgmxyysd"<1204074991@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [chchlsh/MusicBox] 音符频率如何算？ (#1)




这个就涉及到乐理了，我不是专业搞音乐的，对乐理其实也不太懂，但从网上看的意思是相邻的两个半音之比是相等的，而根据十二平均律，从1到高音1之间一共有12个半音，这样我们就能根据前面音的频率来计算后面音的频率了，具体怎么算嘛，还是百度吧，我也是业余的
